import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from './AuthProvider';
import { Session } from 'next-auth';
import Navbar from './components/navbar/Navbar';
import './index.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Insta Insight',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: any,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider session={session}>
        <div>
        <Navbar/>
        {children}
        </div>
      </AuthProvider>
      </body>
    </html>
  )
}
